const AdminActionTypes = {
    ADMIN_GET_ALL_USERS_ORDERS_START: 'ADMIN_GET_ALL_USERS_ORDERS_START',
    ADMIN_GET_ALL_USERS_ORDERS_SUCCESS: 'ADMIN_GET_ALL_USERS_ORDERS_SUCCESS',
    ADMIN_GET_ALL_USERS_ORDERS_FAILURE: 'ADMIN_GET_ALL_USERS_ORDERS_FAILURE',
    ADMIN_GET_ALL_USERS_START: 'ADMIN_GET_ALL_USERS_START',
    ADMIN_GET_ALL_USERS_SUCCESS: 'ADMIN_GET_ALL_USERS_SUCCESS',
    ADMIN_GET_ALL_USERS_FAILURE: 'ADMIN_GET_ALL_USERS_FAILURE',
    ADMIN_GET_ALL_ORDERS_START: 'ADMIN_GET_ALL_ORDERS_START',
    ADMIN_GET_ALL_ORDERS_SUCCESS: 'ADMIN_GET_ALL_ORDERS_SUCCESS',
    ADMIN_GET_ALL_ORDERS_FAILURE: 'ADMIN_GET_ALL_ORDERS_FAILURE',
}

export default AdminActionTypes;